name: zulip
version: 1.8.2
summary: Zulip
description: Zulip Desktop Client for Linux
confinement: strict
grade: stable
icon: ../build/icon.png
apps:
  zulip:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/zulip
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
    source: ../dist/linux-unpacked
    after:
      - desktop-gtk2
